### PR TITLE
Fix MODULEPATH for HPC CentOS image

### LINKED ISSUE #285: Set /usr/share/Modules/modulefiles in the default module use path
with Lmod being installed it would be useful to add the path containing the modules from the HPC image in the default module path
/usr/share/Modules/modulefiles

### PR DESCRIPTION
**Pull request by ltalirz**
fixes #285 

The current `MODULEPATH` on the `azhop-centos79-v2-rdma-gpgpu` az-hop image is
```
$ echo $MODULEPATH
/etc/modulefiles:/usr/share/modulefiles:/usr/share/modulefiles/Linux:/usr/share/modulefiles/Core:/usr/share/lmod/lmod/modulefiles/Core
```
However, `/usr/share/modulefiles` is actually empty
```
$ ls /usr/share/modulefiles/
$
```

The actual modules of the CentOS-HPC image are here:
```
$ ls /usr/share/Modules/modulefiles/
amd  dot  gcc-9.2.0  module-git  module-info  modulefiles  modules  mpi  null  use.own
```

P.S. I don't know where the `/Linux`, `/Core`, ... additions to the `$MODULEPATH` come from. It seems to me they don't apply to the HPC CentOS image.

### CODE REVIEW

**Comment by ltalirz** [comment]
Making the change in an existing setup works; haven't tested deploying it via ansible yet

File: playbooks/roles/cyclecloud_cluster/projects/common/cluster-init/scripts/5-default.sh.j2 [hunk 1]
```diff
@@ -29,3 +29,6 @@ esac
 if [ ! -d /usr/share/Modules ]; then
```
Comment (ltalirz) [inline playbooks/roles/cyclecloud_cluster/projects/common/cluster-init/scripts/5-default.sh.j2:29]: This folder currently exists on the HPC CentOS image, i.e. the symlink is not created.
Not quite sure what purpose this serves

**Review by xpillons — APPROVED** [review]
